Added More endpoints and improved previous ones
tovade-dev/api pull request #3
Opened 2022-12-15 06:49 UTC by TajuModding

2022-12-15 14:46 UTC, tovade requested changes

2022-12-15 14:46 UTC, tovade commented on src/routes/info.js
> +      pattern: '/utility/covid?country=[country]'
Why is there a pattern here?

2022-12-15 16:19 UTC, TajuModding commented
i will remove that its from my API I didn't see that thing 
![image](https://user-images.githubusercontent.com/73745640/207912631-8b7f5038-287b-43ec-b15a-d5afe7195c03.png)

2022-12-18 14:22 UTC, tovade approved these changes
Looks good to me

2022-12-18 14:22 UTC, merged